# Generated by Django 4.1 on 2022-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.ManyToManyField(related_name='students', to='students.activity'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(upload_to='media/student_profile_photos'),
        ),
    ]
