# Generated by Django 4.1 on 2022-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_activity_students_student_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activities',
            field=models.ManyToManyField(null=True, related_name='students', to='students.activity'),
        ),
    ]
