version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: gunicorn root.wsgi -b 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "9000:8000"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    env_file:
      - .env
volumes:
  static_volume:
  media_volume:
